openapi: 3.0.1
info:
  title: YALSE Core
  description: 'Yet Another Local Search Engine'
  contact:
    email: iaga84@gmail.com
  license:
    name: MIT License
  version: 0.1.0
servers:
  - url: http://localhost:8000/api
paths:
  /library/scan:
    put:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.scan_library
      responses:
        202:
          description: request accepted
  /library/metadata/scan:
    put:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.scan_library_metadata
      responses:
        202:
          description: request accepted
  /library/content/scan:
    put:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.scan_library_content
      responses:
        202:
          description: request accepted
  /library/stats:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_library_stats
      responses:
        200:
          description: successful operation
  /library/stats/extensions:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_library_stats_extensions
      responses:
        200:
          description: successful operation
  /library/stats/extensions/size:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_library_stats_extensions_size
      responses:
        200:
          description: successful operation
  /library/size:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_library_size
      responses:
        200:
          description: successful operation
  /library/index:
    delete:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.reset_library
      responses:
        204:
          description: index deleted
  /document/download:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.download
      parameters:
        - in: query
          name: id
          schema:
            type: string
      responses:
        200:
          description: A PDF file
          content:
            application/*:
              schema:
                type: string
                format: binary
  /documents/search:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.search
      parameters:
        - in: query
          name: query
          schema:
            type: string
      responses:
        200:
          description: successful operation
  /documents/duplicates:
    delete:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.delete_duplicate_files
      responses:
        202:
          description: request accepted
  /documents/missing:
    delete:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.delete_missing_documents
      responses:
        202:
          description: request accepted
  /queue/stats:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_queue_stats
      responses:
        200:
          description: successful operation
  /queue/workers:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_workers_stats
      responses:
        200:
          description: successful operation
  /database:
    put:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.create_database
      responses:
        202:
          description: request accepted
  /database/records:
    get:
      summary: WIP
      description: WIP
      operationId: yalse_core.api.get_database_records
      responses:
        200:
          description: request accepted



